### ISSUE TITLE
Exclude 404 error page from sitemap indexing

### ISSUE THREAD

**Issue by mskian** [JacobSNGoodwin/nuxt-ghost-starter#17]
Hi,

Today I noticed while generating a sitemap via `@nuxtjs/sitemap` Module it include the dynamically generated 404 error page `(pages/404.vue)`
I used the module exclude option it does not exclude the 404 error page from the sitemap

**Comment by mskian** [comment]
Temporarily - I remove the Dynamic 404 error page option and add `404.html` file in `static`
it working well & while opening the incorrect/wrong URL it showed the 404 Error Page perfectly

**Comment by JacobSNGoodwin** [comment]
@mskian, thanks for the feedback. I'm going to try to update this template to handle the most recent Ghost updates and I'll see if there's a way to handle the static and dynamic cases.

**Comment by JacobSNGoodwin** [comment]
@mskian,

It appears the issue is that any page generated in the generate.routes function (generateRoutes utility in nuxt.config.js) cannot be excluded. I tried with many different routes.

However, the pages/404.vue page does not actually need any data passed to it. I had previously passed props to the component, but that was leftover from copying and pasting the layouts/error.vue component. That component (error.vue) does need to accept the error property that is passed when the error function is called if there is failure to fetch data when running the application in universal mode. 

In the end, the 404.vue page does not need to be dynamic. Therefore, I'm going to remove it from the generateRoutes function. Then you will be able to exclude 404. 

Anyhow, you probably don't need this anymore, but I learned something.. and maybe you will have, too.

I'm going to add a PR adding the sitemap module and a commented out exclude array in the sitemap config.
