### ISSUE TITLE
TypeError: Cannot read property 'twitter' of null

### ISSUE THREAD

**Issue by mskian** [JacobSNGoodwin/nuxt-ghost-starter#7]
`TypeError: Cannot read property 'twitter' of null`

```bash
npm run generate
```

Got this Error While generating a Static Page For Pages
Post are generated to HTML Pages Successfully

also got the anthor warning 

```
ERROR  (node:5670) DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead 
```

**Comment by JacobSNGoodwin** [comment]
Thanks for reporting. I'll go ahead and see if I need to add a null check. I'm pretty swamped, but it _should_ be easy enough to fix.

**Comment by mskian** [comment]
@Maxbrain0  Seems it Missing the API Import for Pages right?

**Comment by JacobSNGoodwin** [comment]
@mskian 

As far as I can tell right now, the problem is that in the [pages/_slug.vue](https://github.com/Maxbrain0/nuxt-ghost-starter/blob/master/pages/_slug.vue), I'm loading meta data for pages and posts in the same manner. However (as of my current version of Ghost at least, maybe it has been updated), there does not appear to be a primary author for pages. So we have a problem on line 41 since this.post does not have a primary_author.

`{ hid: 'twitter:creator', name: 'twitter:creator', content: this.post.primary_author.twitter }`

The actual payload for the page is created in [util/ghost](https://github.com/Maxbrain0/nuxt-ghost-starter/blob/master/util/ghost.js) at line 105. If I log the data in page, primary_author is indeed null.

Still deciding the best fix here and I'm open to suggestions. Maybe I just create a separate vue component for pages vs posts.

**Comment by mskian** [comment]
yes separate `vue` for pages is best and easy to understand  just add like tag and author page concept
also found this error on console.log 

```
The FetchEvent for "https://blog.jacobsngoodwin.com/" resulted in a network error response: an object that was not a Response was passed to respondWith().
```

**Comment by JacobSNGoodwin** [comment]
> yes separate `vue` for pages is best and easy to understand just add like tag and author page concept
> also found this error on console.log
> 
> ```
> The FetchEvent for "https://blog.jacobsngoodwin.com/" resulted in a network error response: an object that was not a Response was passed to respondWith().
> ```

Ok,  in the future, I'd appreciate if you create a separate issue and describe how you arrived at the result given. If you provide a description like "I did _____, and got the following warning/error," that would help.

**Comment by mskian** [comment]
Just open URL at first time I just check browser log without refresh that time I spotted the yellow warning message if refresh the page it's gone

**Comment by mskian** [comment]
> I'd appreciate if you create a separate issue and describe how you arrived at the result given. If you provide a description like "I did _____, and got the following warning/error," that would help.

#8

**Comment by JacobSNGoodwin** [comment]
It turns out I had a typo in the call to pages. 

I made the call as follows. Since I misspelled "include," the primary author data was not returned, and therefore primary_author was null for pages. I didn't know have this typo in calls to posts, so the SEO head data was working for those pages.

`
const pages = await api.pages.browse({
    limit: 'all',
    inlcude: 'authors,tags'
  })
`

I'll merge the fix shortly. Thanks for spotting this.
